### ISSUE TITLE
UI Design and Functionality

### ISSUE THREAD

**Issue by TheeOnlyJuan** [cs130-w21/21#6]
## Epic
The UI will be how the user interacts with our app to set up a room and make decisions between options. 

User Actions:

The user should be able to use the menu to set up a room to decide on options.

The user should be able to swipe a card left or right until they are out of cards.

## User Stories
- [x] Main Menu #7
- [x] Room Setup #8
- [x] Swipe Cards #9
- [x] Options/Results Frontend #14

**Comment by johnnthough** [comment]
Hello Do you need a UI designer?
